# Generated by Django 5.2.8 on 2025-11-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed_to_updates',
            field=models.BooleanField(default=True, help_text='Check this box to receive periodic updates and newsletters.', verbose_name='Subscribe to Email Updates'),
        ),
    ]
