# Generated by Django 5.2.5 on 2025-08-31 23:52

import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post Date'),
        ),
    ]
