# Generated by Django 5.2.5 on 2025-12-23 19:47

import blog.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_allow_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('chart', 2)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'blank': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': blog.blocks.get_plotly_figures}), 2: ('wagtail.blocks.StructBlock', [[('script_selection', 1)]], {})}),
        ),
    ]
