# Generated by Django 5.2.5 on 2025-09-01 00:00

from django.db import migrations, models
from django.utils.html import strip_tags

def strip_intro_html(apps, schema_editor):
    HomePage = apps.get_model("home", "HomePage")  # adjust "home" to your app name
    for page in HomePage.objects.all():
        if page.intro:
            page.intro = strip_tags(page.intro)
            page.save()




class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_remove_blogindexpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
        migrations.RunPython(strip_intro_html),
    ]
