# Generated by Django 5.2.9 on 2025-12-29 21:54

import blog.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('chart', 2), ('dash', 6)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'blank': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': blog.blocks.get_plotly_figures}), 2: ('wagtail.blocks.StructBlock', [[('script_selection', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Enter the app suffix only (e.g., 'app1/'). Base URL https://dash.jag-economics.com is added automatically.", 'label': 'App Path'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'For accessibility/screen readers', 'required': False}), 5: ('wagtail.blocks.IntegerBlock', (), {'default': 600, 'help_text': 'Height in pixels'}), 6: ('wagtail.blocks.StructBlock', [[('url_suffix', 3), ('title', 4), ('height', 5)]], {})}),
        ),
    ]
