# Generated by Django 5.2.5 on 2025-09-01 00:08

from django.db import migrations, models
from django.utils.html import strip_tags

def strip_intro_html(apps, schema_editor):
    HomePage = apps.get_model("blog", "BlogPage")  # adjust "home" to your app name
    for page in HomePage.objects.all():
        if page.intro:
            page.intro = strip_tags(page.intro)
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(strip_intro_html),
    ]


