"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
from decouple import Config, RepositoryEnv

base_config = Config(RepositoryEnv(".env.base"))

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)
GRAPH_DIR_NAME = base_config('GRAPH_DIR_NAME')
GRAPH_DIR = os.path.join(base_config('GRAPH_ROOT_DIR'), GRAPH_DIR_NAME)

# GRAPH SETTINGS
if os.path.exists(GRAPH_DIR):
    sys.path.append(GRAPH_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "base",
    "blog",
    "core",
    "portfolio",
    "home",
    "search",
    "users",
    "newsletter",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "wagtail_newsletter",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "widget_tweaks",
    "django_unused_media",
    "django_recaptcha",
    "django_comments_xtd",
    "django_comments",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

# Required for Django Comments to work. Points to the root site ID.
SITE_ID=2

# URLS
ROOT_URLCONF = "mysite.urls"
LOGIN_REDIRECT_URL = 'site_root'
SAFE_LOGOUT_REDIRECT = 'site_root'
HOME_URL = 'site_root'

# List of URL names or path prefixes that require authentication
PROTECTED_URL_PATHS = [
    "/account/profile",
    "/admin/"
    # Add any other URL names that require login, e.g., 'dashboard'
]


# Templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wagtail.contrib.settings.context_processors.settings",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# User settings
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = [
    # Allows users to login with email or username.
    'mysite.auth_backends.EmailOrUsernameBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "users.User"

# The default duration for a non-session-ending logout (e.g., 2 weeks in seconds)
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14 # 1,209,600 seconds (2 weeks)

# Default setting: Session expires when the browser closes.
# We override this in the view *only* if the user checks "remember me".
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings
WAGTAIL_SITE_NAME = base_config("WAGTAIL_SITE_NAME")

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "https://jag-economics.com"

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']


# Mailchimp for newsletter
WAGTAIL_NEWSLETTER_RECIPIENTS_MODEL = "wagtail_newsletter.NewsletterRecipients"
WAGTAIL_NEWSLETTER_CAMPAIGN_BACKEND = "wagtail_newsletter.campaign_backends.mailchimp.MailchimpCampaignBackend"
WAGTAIL_NEWSLETTER_MAILCHIMP_API_KEY= base_config("WAGTAIL_NEWSLETTER_MAILCHIMP_API_KEY")
WAGTAIL_NEWSLETTER_FROM_NAME=base_config("WAGTAIL_NEWSLETTER_FROM_NAME")
WAGTAIL_NEWSLETTER_REPLY_TO=base_config("WAGTAIL_NEWSLETTER_REPLY_TO")
WAGTAIL_NEWSLETTER_CACHE_TIMEOUT = 300  # 5 minutes

# Newsletter General Settings
NEWSLETTER_AUDIENCE_NAME=base_config("NEWSLETTER_AUDIENCE_NAME")

# Comment settings on blog posts
COMMENTS_APP = "django_comments_xtd"
COMMENTS_XTD_FORM_CLASS = 'blog.forms.FilteredCommentForm'
COMMENTS_XTD_MAX_THREAD_LEVEL = 1
COMMENTS_XTD_LIST_ORDER = ('-thread_id', 'order')
COMMENTS_XTD_CONFIRM_EMAIL = False
COMMENTS_XTD_SALT = (b"Timendi causa est nescire. "
                    b"Aequam memento rebus in arduis servare mentem.")
COMMENTS_XTD_APP_MODEL_OPTIONS = {
    'default': {
        'allow_flagging': True,
        'allow_feedback': True,
        'show_feedback': False,
        'who_can_post': 'all'
    },
}
